username: admin
password: NokiaSrl1!
insecure: false
skip-verify: true
timeout: 10s

targets:
  srlswitch:
    address: srlswitch:57400
  
  
subscriptions:    
  srl-if-stats:
    mode: stream
    stream-mode: sample
    sample-interval: 5s
    paths:
      - /interface[name=*]/statistics/in-multicast-packets
      - /interface[name=*]/statistics/out-multicast-packets
      - /interface[name=*]/subinterface[index=*]/ipv6/statistics/in-error-packets
      - /interface[name=*]/subinterface[index=*]/ipv6/statistics/out-error-packets
      - /interface[name=*]/subinterface[index=*]/ipv6/statistics/in-forwarded-packets
      - /interface[name=*]/subinterface[index=*]/ipv6/statistics/out-forwarded-packets
                               
outputs:
  file_output:
    type: file
    filename: /data/stats_ifaces.json
    format: json
    split-events: true   

  prom-output:
    type: prometheus
    listen: :9273         

    
