username: admin
password: NokiaSrl1!
insecure: false
skip-verify: true
timeout: 10s

targets:
  srlswitch:
    address: srlswitch:57400
    subscriptions:
      - srlswitch-if-stats
    outputs:
      - prom-output
      - file_output
  srlrouter:
    address: srlswitch:57400
    subscriptions:
      - srlrouter-if-stats
    outputs:
      - prom-output
      
subscriptions:
  srlswitch-if-stats:
    mode: stream
    stream-mode: sample
    sample-interval: 5s
    paths:
      - /interface[name=*]/statistics/in-multicast-packets
      - /interface[name=*]/statistics/out-multicast-packets
  srlrouter-if-stats:
    mode: stream
    stream-mode: sample
    sample-interval: 5s
    paths:
      - /interface[name=*]/subinterface[index=*]/ipv6/statistics/in-error-packets
      - /interface[name=*]/subinterface[index=*]/ipv6/statistics/in-forwarded-packets

outputs:

  prom-output:
    type: prometheus
    listen: :9273         
  file_output:
    type: file
    filename: /data/stats_ifaces.json
    format: json
    split-events: true   
